---
language: node_js
sudo: false
node_js:
  - stable
cache:
  directories:
    - bower_components
    - node_modules

deploy:
  provider: releases
  api_key:
    secure: r14+zZDSUKBwf4Gq9kni1wY0r53O40rqG6W+uFZ7b2mWpdaV6/UEEBrH2PpISt3k9Sge3OgwymUTVmky6q9MQnKpGuQNGpyzlLLsvCSW59VjW/1Ivf6KG0GN179e+f7g9QFDE+eNrDnREcSdeyAChxRNiqjoIbdh+qhY9t6I+EB0Db4eTqvp+9hXu4gFx3e+CYPiz2LkfKo8G1jubbHfrzaxQAtuvxzl0kYfvZTCW6+R9oBaQOPPv2bwiOfJSdD4pw31wQNseCr7JRsCRTYK8/kmw48E035hvrLaFxgvpGQ5OgRNmeUIuG5JoNrjTjpatEkW/RD574YCyRMe+MDQVjWpMyh2IuUkp5qvfFUVtHiObwHN08jhCZWNr72zzMpDlCWx7YDiI//dTUPg771ZtjO8ALnBoXHCOVYgMda+R1iVo3tptd3YVNkzEpf2s5IbJf5L3EKUtTmZtKm0Z9iKQrHyYSR6zKbwfJppUvbYsK7AmZGtPkLVk7+f0lPVNNNSr1/hmLybE60qGqqQXpaEiP8FPa1qF7yGfXdP687Rx+D1Oq/bQCsgUn7DW4JcdjPMF2GSi1vDEqSOfYbqU0R8ZF5Tjfi9UB/Iuf4ehc54iSq18hDDPExNC7mXfJjx70h23UoLhYznHRu/Qa4O2Ktl51ugxkcuIFSx3L/kmunu6Zs=
  file: js/gist-async.min.js
  on:
    tags: true
